/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as MeusTimesRouteImport } from './routes/meus-times'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CampeonatosRouteImport } from './routes/campeonatos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MeusTimesNovoRouteImport } from './routes/meus-times.novo'
import { Route as MeusTimesIdRouteImport } from './routes/meus-times.$id'
import { Route as CampeonatosIdRouteImport } from './routes/campeonatos.$id'
import { Route as AdminInscricoesRouteImport } from './routes/admin.inscricoes'
import { Route as AdminCampeonatosRouteImport } from './routes/admin.campeonatos'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const MeusTimesRoute = MeusTimesRouteImport.update({
  id: '/meus-times',
  path: '/meus-times',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CampeonatosRoute = CampeonatosRouteImport.update({
  id: '/campeonatos',
  path: '/campeonatos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeusTimesNovoRoute = MeusTimesNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => MeusTimesRoute,
} as any)
const MeusTimesIdRoute = MeusTimesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MeusTimesRoute,
} as any)
const CampeonatosIdRoute = CampeonatosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CampeonatosRoute,
} as any)
const AdminInscricoesRoute = AdminInscricoesRouteImport.update({
  id: '/admin/inscricoes',
  path: '/admin/inscricoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCampeonatosRoute = AdminCampeonatosRouteImport.update({
  id: '/admin/campeonatos',
  path: '/admin/campeonatos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/campeonatos': typeof CampeonatosRouteWithChildren
  '/login': typeof LoginRoute
  '/meus-times': typeof MeusTimesRouteWithChildren
  '/perfil': typeof PerfilRoute
  '/register': typeof RegisterRoute
  '/admin/campeonatos': typeof AdminCampeonatosRoute
  '/admin/inscricoes': typeof AdminInscricoesRoute
  '/campeonatos/$id': typeof CampeonatosIdRoute
  '/meus-times/$id': typeof MeusTimesIdRoute
  '/meus-times/novo': typeof MeusTimesNovoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/campeonatos': typeof CampeonatosRouteWithChildren
  '/login': typeof LoginRoute
  '/meus-times': typeof MeusTimesRouteWithChildren
  '/perfil': typeof PerfilRoute
  '/register': typeof RegisterRoute
  '/admin/campeonatos': typeof AdminCampeonatosRoute
  '/admin/inscricoes': typeof AdminInscricoesRoute
  '/campeonatos/$id': typeof CampeonatosIdRoute
  '/meus-times/$id': typeof MeusTimesIdRoute
  '/meus-times/novo': typeof MeusTimesNovoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/campeonatos': typeof CampeonatosRouteWithChildren
  '/login': typeof LoginRoute
  '/meus-times': typeof MeusTimesRouteWithChildren
  '/perfil': typeof PerfilRoute
  '/register': typeof RegisterRoute
  '/admin/campeonatos': typeof AdminCampeonatosRoute
  '/admin/inscricoes': typeof AdminInscricoesRoute
  '/campeonatos/$id': typeof CampeonatosIdRoute
  '/meus-times/$id': typeof MeusTimesIdRoute
  '/meus-times/novo': typeof MeusTimesNovoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/campeonatos'
    | '/login'
    | '/meus-times'
    | '/perfil'
    | '/register'
    | '/admin/campeonatos'
    | '/admin/inscricoes'
    | '/campeonatos/$id'
    | '/meus-times/$id'
    | '/meus-times/novo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/campeonatos'
    | '/login'
    | '/meus-times'
    | '/perfil'
    | '/register'
    | '/admin/campeonatos'
    | '/admin/inscricoes'
    | '/campeonatos/$id'
    | '/meus-times/$id'
    | '/meus-times/novo'
  id:
    | '__root__'
    | '/'
    | '/campeonatos'
    | '/login'
    | '/meus-times'
    | '/perfil'
    | '/register'
    | '/admin/campeonatos'
    | '/admin/inscricoes'
    | '/campeonatos/$id'
    | '/meus-times/$id'
    | '/meus-times/novo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampeonatosRoute: typeof CampeonatosRouteWithChildren
  LoginRoute: typeof LoginRoute
  MeusTimesRoute: typeof MeusTimesRouteWithChildren
  PerfilRoute: typeof PerfilRoute
  RegisterRoute: typeof RegisterRoute
  AdminCampeonatosRoute: typeof AdminCampeonatosRoute
  AdminInscricoesRoute: typeof AdminInscricoesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meus-times': {
      id: '/meus-times'
      path: '/meus-times'
      fullPath: '/meus-times'
      preLoaderRoute: typeof MeusTimesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campeonatos': {
      id: '/campeonatos'
      path: '/campeonatos'
      fullPath: '/campeonatos'
      preLoaderRoute: typeof CampeonatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meus-times/novo': {
      id: '/meus-times/novo'
      path: '/novo'
      fullPath: '/meus-times/novo'
      preLoaderRoute: typeof MeusTimesNovoRouteImport
      parentRoute: typeof MeusTimesRoute
    }
    '/meus-times/$id': {
      id: '/meus-times/$id'
      path: '/$id'
      fullPath: '/meus-times/$id'
      preLoaderRoute: typeof MeusTimesIdRouteImport
      parentRoute: typeof MeusTimesRoute
    }
    '/campeonatos/$id': {
      id: '/campeonatos/$id'
      path: '/$id'
      fullPath: '/campeonatos/$id'
      preLoaderRoute: typeof CampeonatosIdRouteImport
      parentRoute: typeof CampeonatosRoute
    }
    '/admin/inscricoes': {
      id: '/admin/inscricoes'
      path: '/admin/inscricoes'
      fullPath: '/admin/inscricoes'
      preLoaderRoute: typeof AdminInscricoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/campeonatos': {
      id: '/admin/campeonatos'
      path: '/admin/campeonatos'
      fullPath: '/admin/campeonatos'
      preLoaderRoute: typeof AdminCampeonatosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CampeonatosRouteChildren {
  CampeonatosIdRoute: typeof CampeonatosIdRoute
}

const CampeonatosRouteChildren: CampeonatosRouteChildren = {
  CampeonatosIdRoute: CampeonatosIdRoute,
}

const CampeonatosRouteWithChildren = CampeonatosRoute._addFileChildren(
  CampeonatosRouteChildren,
)

interface MeusTimesRouteChildren {
  MeusTimesIdRoute: typeof MeusTimesIdRoute
  MeusTimesNovoRoute: typeof MeusTimesNovoRoute
}

const MeusTimesRouteChildren: MeusTimesRouteChildren = {
  MeusTimesIdRoute: MeusTimesIdRoute,
  MeusTimesNovoRoute: MeusTimesNovoRoute,
}

const MeusTimesRouteWithChildren = MeusTimesRoute._addFileChildren(
  MeusTimesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampeonatosRoute: CampeonatosRouteWithChildren,
  LoginRoute: LoginRoute,
  MeusTimesRoute: MeusTimesRouteWithChildren,
  PerfilRoute: PerfilRoute,
  RegisterRoute: RegisterRoute,
  AdminCampeonatosRoute: AdminCampeonatosRoute,
  AdminInscricoesRoute: AdminInscricoesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
