name: infestation-championship

services:
  frontchamp:
    build:
      context: ./www/infestation-championship
      dockerfile: Dockerfile
    container_name: front-championship
    ports:
      - "7181:7181"
    environment:
      NODE_ENV: development
      PORT: 7181
      VITE_API_URL: http://backchamp:7180/api
    #depends_on:
    #  - api
    networks:
      - infestation-network

  backchamp:
    build:
      context: ./API
      dockerfile: Dockerfile
    container_name: backend-championship
    ports:
      - "7180:7180"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:7180
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=ChampionshipDB;User Id=sa;Password=DOw0zZKiq75B;TrustServerCertificate=True;Encrypt=False;
      - Jwt__Key=x+bj5OC/oYLGxbDy1k8MK5GzpCwsQ/XUsaim+Ojpu9I=
      - Jwt__Issuer=http://localhost:7180
      - Jwt__Audience=http://localhost:7180
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - infestation-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: DOw0zZKiq75B
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data1:/var/opt/mssql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "DOw0zZKiq75B", "-C", "-Q", "SELECT 1"]
      interval: 3s
      timeout: 5s
      retries: 3
    networks:
      - infestation-network

networks:
  infestation-network:
    driver: bridge

volumes:
  sqlserver_data1: